# Generated by Django 3.1.5 on 2021-02-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210202_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'All Accounts'},
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
