# Generated by Django 3.1.6 on 2021-02-25 21:56

import blogPost.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to=blogPost.models.upload_location),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
